# $NetBSD$

DISTNAME=	facile-1.1.3
CATEGORIES=	devel
MASTER_SITES=	http://opti.recherche.enac.fr/facile/

HOMEPAGE=	http://opti.recherche.enac.fr/facile/distrib/
COMMENT=	Functional Constraint Library
LICENSE=	gnu-lgpl-v2.1

HAS_CONFIGURE=	yes
USE_LANGUAGES=	# none
USE_TOOLS+=	gmake

BUILD_TARGET=	compile

.include "../../lang/ocaml/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
