# $NetBSD$

DISTNAME=	scim-sayura-0.3.3
CATEGORIES=	inputmethod
MASTER_SITES=	http://www.sayura.net/im/

HOMEPAGE=	http://www.sayura.net/im/
COMMENT=	Sayura Sinhala input method for SCIM
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++
USE_TOOLS+=	pkg-config

.include "../../inputmethod/scim/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
