$NetBSD$

* set xxx_INCLUDE_DIRS (semicolon separated) to proper variable

--- ConfigureChecks.cmake.orig	2019-02-05 11:46:19.000000000 +0000
+++ ConfigureChecks.cmake
@@ -149,7 +151,8 @@ if( BUILD_LIBTDENETWORK OR BUILD_CERTMAN
   tde_save( CMAKE_REQUIRED_LIBRARIES )
   string( REGEX REPLACE "-include tqt.h" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" )
   # See FIXME above regarding -D_FILE_OFFSET_BITS=64
-  set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GPGME_INCLUDE_DIRS} -D_FILE_OFFSET_BITS=64")
+  set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FILE_OFFSET_BITS=64")
+  set( CMAKE_INCLUDE_DIRS "${CMAKE_INCLUDE_DIRS};$<$COMPILER_LANGUAGE:CXX>:GPGME_INCLUDE_DIRS>")
   set( CMAKE_REQUIRED_LIBRARIES "${GPGME_LIBRARIES}")
 
   # check for GPGME_KEYLIST_MODE_VALIDATE
