# $NetBSD$

DISTNAME=	rr-1.2.1
CATEGORIES=	devel

HOMEPAGE=	https://rr.github.io/rr/
COMMENT=	Test double framework for Ruby with succinct syntax
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
