# $NetBSD$

DISTNAME=	fcitx-table-other-0.2.3
CATEGORIES=	inputmethod
MASTER_SITES=	http://download.fcitx-im.org/fcitx-table-other/
EXTRACT_SUFX=	.tar.xz

HOMEPAGE=	http://fcitx-im.org/
COMMENT=	Other table for Fcitx
LICENSE=	gnu-gpl-v3

USE_CMAKE=	yes
USE_LANGUAGES=	# none
USE_TOOLS+=	msgfmt pkg-config

ICON_THEMES=	yes

.include "../../inputmethod/fcitx/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
