# $NetBSD: Makefile.common,v 1.7 2017/08/16 21:22:13 wiz Exp $
#
# used by inputmethod/input-pad/Makefile
# used by inputmethod/py-input-pad/Makefile

DISTNAME=	input-pad-1.0.3
CATEGORIES=	inputmethod
MASTER_SITES=	https://github.com/fujiwarat/input-pad/releases/download/${PKGVERSION_NOREV}/

HOMEPAGE=	https://github.com/fujiwarat/input-pad/wiki
LICENSE=	gnu-lgpl-v2.1

DISTINFO_FILE=	${.CURDIR}/../../inputmethod/input-pad/distinfo
PATCHDIR=	${.CURDIR}/../../inputmethod/input-pad/patches
