# $NetBSD$
#
# System-supplied tools for the Linux operating system.

TOOLS_PLATFORM.[?=		[			# shell builtin
TOOLS_PLATFORM.awk?=		${TOOLS_PLATFORM.gawk}
TOOLS_PLATFORM.autopoint?=	/usr/local/bin/autopoint
TOOLS_PLATFORM.basename?=	/bin/basename
TOOLS_PLATFORM.bash?=		/bin/bash
TOOLS_PLATFORM.bison?=		/bin/bison
TOOLS_PLATFORM.bison-yacc?=	/bin/bison -y
TOOLS_PLATFORM.bzcat?=		/bin/bzcat
TOOLS_PLATFORM.bzip2?=		/bin/bzip2
TOOLS_PLATFORM.cat?=		/bin/cat
TOOLS_PLATFORM.chgrp?=		${TRUE}
TOOLS_PLATFORM.chmod?=		/bin/chmod
TOOLS_PLATFORM.chown?=		/bin/chown
TOOLS_PLATFORM.cmp?=		/bin/cmp
TOOLS_PLATFORM.cp?=		/bin/cp
TOOLS_PLATFORM.csh?=		# missing
TOOLS_PLATFORM.curl?=		# missing
TOOLS_PLATFORM.cut?=		/bin/cut
TOOLS_PLATFORM.date?=		/bin/date
TOOLS_PLATFORM.diff?=		/bin/diff
TOOLS_PLATFORM.diff3?=		/bin/diff3
TOOLS_PLATFORM.dirname?=	/bin/dirname
TOOLS_PLATFORM.echo?=		echo			# shell builtin
TOOLS_PLATFORM.egrep?=		/bin/egrep
TOOLS_PLATFORM.env?=		/bin/env
TOOLS_PLATFORM.expr?=		/bin/expr
TOOLS_PLATFORM.false?=		false			# shell builtin
TOOLS_PLATFORM.fgrep?=		/bin/fgrep
TOOLS_PLATFORM.file?=		# missing
TOOLS_PLATFORM.find?=		/bin/find
TOOLS_PLATFORM.gawk?=		/bin/awk
TOOLS_PLATFORM.gettext?=	/usr/local/bin/gettext
TOOLS_PLATFORM.gm4?=		/usr/bin/m4
TOOLS_PLATFORM.gmake?=		/bin/make
TOOLS_PLATFORM.grep?=		/bin/grep
TOOLS_PLATFORM.gsed?=		/usr/local/bin/sed
TOOLS_PLATFORM.goelim?=		# missing
TOOLS_PLATFORM.gtar?=		/bin/tar
TOOLS_PLATFORM.gunzip?=		/bin/gzip -df
TOOLS_PLATFORM.gzcat?=		/bin/gzip -cd
TOOLS_PLATFORM.gzip?=		/bin/gzip -nf ${GZIP}
TOOLS_PLATFORM.head?=		/bin/head
TOOLS_PLATFORM.hostname?=	/bin/hostname
TOOLS_PLATFORM.id?=		# missing
TOOLS_PLATFORM.ident?=		# missing
TOOLS_PLATFORM.install?=	# missing
TOOLS_PLATFORM.install-info?=	# missing
TOOLS_PLATFORM.ldconfig?=	# missing
TOOLS_PLATFORM.ln?=		/bin/ln
TOOLS_PLATFORM.ls?=		/bin/ls
TOOLS_PLATFORM.m4?=		${TOOLS_PLATFORM.gm4}
TOOLS_PLATFORM.mail?=		# missing
TOOLS_PLATFORM.makeinfo?=	# missing
TOOLS_PLATFORM.mkdir?=		/bin/mkdir -p
TOOLS_PLATFORM.mktemp?=		/bin/mktemp
TOOLS_PLATFORM.msgconv?=	/usr/local/bin/msgconv
TOOLS_PLATFORM.msgfmt?=		/usr/local/bin/msgfmt
TOOLS_PLATFORM.msgmerge?=	/usr/local/bin/msgmerge
TOOLS_PLATFORM.mv?=		/bin/mv
TOOLS_PLATFORM.nice?=		# missing
TOOLS_PLATFORM.nroff?=		# missing
TOOLS_PLATFORM.openssl?=	# missing
# Don't use GNU patch
#TOOLS_PLATFORM.patch?=		/usr/local/bin/patch
TOOLS_PLATFORM.printf?=		/bin/printf
TOOLS_PLATFORM.pwd?=		/bin/pwd
TOOLS_PLATFORM.readelf?=	/usr/bin/readelf
TOOLS_PLATFORM.readlink?=	/bin/readlink
TOOLS_PLATFORM.rm?=		/bin/rm
TOOLS_PLATFORM.rmdir?=		/bin/rmdir
TOOLS_PLATFORM.sdiff?=		/bin/sdiff
TOOLS_PLATFORM.sed?=		${TOOLS_PLATFORM.gsed}
TOOLS_PLATFORM.sh?=		/bin/sh
TOOLS_PLATFORM.sleep?=		/bin/sleep
TOOLS_PLATFORM.soelim?=		# missing
TOOLS_PLATFORM.sort?=		/bin/sort
TOOLS_PLATFORM.strip?=		/usr/bin/strip
TOOLS_PLATFORM.tail?=		/bin/tail
TOOLS_PLATFORM.tar?=		${TOOLS_PLATFORM.gtar}
TOOLS_PLATFORM.tbl?=		# missing
TOOLS_PLATFORM.tee?=		/bin/tee
TOOLS_PLATFORM.test?=		test			# shell builtin
TOOLS_PLATFORM.touch?=		/bin/touch
TOOLS_PLATFORM.tr?=		/bin/tr
TOOLS_PLATFORM.true?=		true			# shell builtin
TOOLS_PLATFORM.tsort?=		/ubin/tsort
TOOLS_PLATFORM.uniq?=		/bin/uniq
TOOLS_PLATFORM.unlink?=		/bin/unlink
TOOLS_PLATFORM.wc?=		/bin/wc
TOOLS_PLATFORM.wget?=		/boot/programs/tools/wget.app
TOOLS_PLATFORM.xargs?=		/bin/xargs -r
TOOLS_PLATFORM.xgettext?=	/usr/local/bin/xgettext
TOOLS_PLATFORM.yacc?=		/bin/bison -y
TOOLS_PLATFORM.xz?=		# missing
TOOLS_PLATFORM.xzcat?=		# missing

