# $NetBSD$

DISTNAME=	fcitx-table-extra-0.3.7
CATEGORIES=	inputmethod
MASTER_SITES=	http://download.fcitx-im.org/fcitx-table-extra/
EXTRACT_SUFX=	.tar.xz

HOMEPAGE=	http://fcitx-im.org/
COMMENT=	Extra table for Fcitx
LICENSE=	gnu-gpl-v2

USE_CMAKE=	yes
USE_LANGUAGES=	# none
USE_TOOLS+=	msgfmt pkg-config

ICON_THEMES=	yes

.include "../../inputmethod/fcitx/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
