# $NetBSD: Makefile.common,v 1.9 2017/08/16 20:45:46 wiz Exp $
#
# used by textproc/mecab-base/Makefile
# used by textproc/java-mecab/Makefile
# used by textproc/p5-mecab/Makefile
# used by textproc/py-mecab/Makefile
# used by textproc/ruby-mecab/Makefile
# used by textproc/mecab-ipadic/Makefile
# used by textproc/mecab-jumandic/Makefile

MECAB_VERSION=	0.996

CATEGORIES=	japanese textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://taku910.github.io/mecab/
