# $NetBSD$

NPM_PKGNAME=	emojione
NPM_PKGVERSION=	2.2.6
CATEGORIES=	www

HOMEPAGE=	http://www.emojione.com/
COMMENT=	The web's firts and only complete open source emoji set
LICENSE=	cc-by-sa-v4.0 AND mit

CHECK_INTERPRETER_SKIP+=	lib/node_modules/emojione/lib/python/emojipy/*.py

.include "../../mk/npm.mk"
.include "../../mk/bsd.pkg.mk"
