# $NetBSD: Makefile,v 1.8 2018/08/16 12:19:54 wiz Exp $

DISTNAME=	npth-1.6
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNUPG:=npth/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	ada@netbsdfr.org
HOMEPAGE=	https://www.gnupg.org/software/npth/index.html
COMMENT=	New Portable Threads Library (nPth)
LICENSE=	gnu-lgpl-v2.1

USE_LANGUAGES=	c99
USE_LIBTOOL=	yes
GNU_CONFIGURE=	yes
TEST_TARGET=	check

.include "../../mk/bsd.pkg.mk"
