# $NetBSD$

DISTNAME=	json-stream-0.2.1
CATEGORIES=	textproc

HOMEPAGE=	http://dgraham.github.io/json-stream/
COMMENT=	Ruby streaming JSON parser that generates SAX-like events
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
