# $NetBSD$

PKGNAME=	mate-extra-1.12
CATEGORIES=	meta-pkgs mate

HOMEPAGE=	http://www.mate-desktop.org/
COMMENT=	Extra packages for MATE desktop environment
LICENSE=	public-domain

META_PACKAGE=	yes

# see http://wiki.mate-desktop.org/status:1.12

DEPENDS+=	mate-core>=${PKGVERSION_NOREV}:../../meta-pkgs/mate-core
DEPENDS+=	atril>=${PKGVERSION_NOREV}:../../print/atril
DEPENDS+=	caja-dropbox>=${PKGVERSION_NOREV}:../../sysutils/caja-dropbox
DEPENDS+=	caja-extensions>=${PKGVERSION_NOREV}:../../sysutils/caja-extensions
DEPENDS+=	engrampa>=${PKGVERSION_NOREV}:../../archivers/engrampa
DEPENDS+=	eom>=${PKGVERSION_NOREV}:../../graphics/eom
DEPENDS+=	mate-applets>=${PKGVERSION_NOREV}:../../x11/mate-applets
DEPENDS+=	mate-icon-theme-faenza>=${PKGVERSION_NOREV}:../../graphics/mate-icon-theme-faenza
DEPENDS+=	mate-indicator-applet>=${PKGVERSION_NOREV}:../../x11/mate-indicator-applet
DEPENDS+=	mate-netbook>=${PKGVERSION_NOREV}:../../wm/mate-netbook
DEPENDS+=	mate-netspeed>=${PKGVERSION_NOREV}:../../sysutils/mate-netspeed
DEPENDS+=	mate-sensors-applet>=${PKGVERSION_NOREV}:../../sysutils/mate-sensors-applet
DEPENDS+=	mate-terminal>=${PKGVERSION_NOREV}:../../x11/mate-terminal
DEPENDS+=	mate-user-guide>=${PKGVERSION_NOREV}:../../misc/mate-user-guide
DEPENDS+=	mate-user-share>=${PKGVERSION_NOREV}:../../sysutils/mate-user-share
DEPENDS+=	mate-utils>=${PKGVERSION_NOREV}:../../misc/mate-utils
DEPENDS+=	mozo>=${PKGVERSION_NOREV}:../../x11/mozo
DEPENDS+=	pluma>=${PKGVERSION_NOREV}:../../editors/pluma
DEPENDS+=	python-caja>=${PKGVERSION_NOREV}:../../sysutils/python-caja

.include "../../mk/bsd.pkg.mk"
