$NetBSD$

* update for compatible with new libpinyin

--- src/eim.h.orig	2013-07-15 20:34:05.000000000 +0000
+++ src/eim.h
@@ -82,10 +82,26 @@ enum FCITX_DICTIONARY {
     FCITX_DICT_HISTORY,
     FCITX_DICT_LIFE,
     FCITX_DICT_NATURE,
-    FCITX_DICT_SCITECH,
+    FCITX_DICT_PEOPLE,
+    FCITX_DICT_SCIENCE,
     FCITX_DICT_SOCIETY,
     FCITX_DICT_SPORT,
-    FCITX_DICT_LAST = FCITX_DICT_SPORT
+    FCITX_DICT_TECHNOLOGY,
+    FCITX_DICT_LAST = FCITX_DICT_TECHNOLOGY
+};
+
+enum FCITX_ZHUYIN_DICTIONARY {
+    FCITX_ZHUYIN_DICT_ART,
+    FCITX_ZHUYIN_DICT_CULTURE,
+    FCITX_ZHUYIN_DICT_ECONOMY,
+    FCITX_ZHUYIN_DICT_GEOLOGY,
+    FCITX_ZHUYIN_DICT_HISTORY,
+    FCITX_ZHUYIN_DICT_LIFE,
+    FCITX_ZHUYIN_DICT_NATURE,
+    FCITX_ZHUYIN_DICT_SCITECH,
+    FCITX_ZHUYIN_DICT_SOCIETY,
+    FCITX_ZHUYIN_DICT_SPORT,
+    FCITX_ZHUYIN_DICT_LAST = FCITX_ZHUYIN_DICT_SPORT
 };
 
 enum FCITX_AMBIGUITY {
@@ -117,6 +133,7 @@ struct FcitxLibPinyinConfig
     boolean amb[FCITX_AMB_LAST + 1];
     boolean cr[FCITX_CR_LAST + 1];
     boolean dict[FCITX_DICT_LAST + 1];
+    boolean dict_zhuyin[FCITX_ZHUYIN_DICT_LAST + 1];
     boolean incomplete;
     boolean chewingIncomplete;
     boolean bTraditionalDataForPinyin;
