# $NetBSD: Makefile.common,v 1.9 2016/03/02 22:59:00 ryoon Exp $
#
# used by inputmethod/ibus/Makefile
# used by inputmethod/ibus-python/Makefile

DISTNAME=	ibus-1.5.14
CATEGORIES=	inputmethod
MASTER_SITES=	https://github.com/ibus/ibus/releases/download/${PKGVERSION_NOREV}/

DISTINFO_FILE=	${.CURDIR}/../../inputmethod/ibus/distinfo
PATCHDIR=	${.CURDIR}/../../inputmethod/ibus/patches

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ibus/ibus/wiki
LICENSE=	gnu-lgpl-v2.1
