===========================================================================
$NetBSD: MESSAGE.module,v 1.4 2016/07/17 15:49:44 jdolecek Exp $

To enable this module, add the following to ${PKG_SYSCONFDIR}/php.ini:

    ${PHP_EXTENSION_DIRECTIVE}=${MODNAME}.so

and make sure extension_dir points to the dir where ${MODNAME}.so is.

Then restart your ${PKG_PHP}-enabled HTTP server to load this module.
===========================================================================
