# $NetBSD$

DISTNAME=	groonga-command-1.3.0
CATEGORIES=	textproc

HOMEPAGE=	https://github.com/groonga/groonga-command
COMMENT=	Ruby library that represents Groonga commands
LICENSE=	gnu-lgpl-v2.1

.include "../../lang/ruby/json.mk"
.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
