# $NetBSD$

DISTNAME=	test-unit-rr-1.0.5
CATEGORIES=	devel

HOMEPAGE=	https://github.com/test-unit/test-unit-rr
COMMENT=	RR adapter for Ruby test-unit
LICENSE=	gnu-lgpl-v2 # or later

#DEPENDS+=	${RUBY_PKGPREFIX}-test-unit>=2.5.2:../../devel/ruby-test-unit
DEPENDS+=	${RUBY_PKGPREFIX}-rr>=1.1.1:../../devel/ruby-rr

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
