# $NetBSD$

DISTNAME=	groonga-command-parser-1.1.4
CATEGORIES=	textproc

HOMEPAGE=	https://github.com/groonga/groonga-command-parser
COMMENT=	Ruby library that parses Groonga commands
LICENSE=	gnu-lgpl-v2.1

DEPENDS+=	${RUBY_PKGPREFIX}-json-stream-[0-9]*:../../textproc/ruby-json-stream
DEPENDS+=	${RUBY_PKGPREFIX}-groonga-command>=1.4.0:../../textproc/ruby-groonga-command

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
