# $NetBSD$
#

DISTNAME=	${PKGNAME:S/-//}
PKGNAME=	dvts-1.0g
CATEGORIES=	multimedia
MASTER_SITES=	http://www.sfc.wide.ad.jp/DVTS/software/
EXTRACT_SUFX=	.tar.bz2

HOMEPAGE=	http://www.sfc.wide.ad.jp/DVTS/
COMMENT=	DV Stream on IEEE1394 Encapsulated into IP
LICENSE=	original-bsd

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
