# $NetBSD$

.include "Makefile.common"

COMMENT=	TQt3 C++ X GUI toolkit
META_PACKAGE=	yes

DEPENDS+=	tqt3-libs>=${TQT3_RELEASE}:../../x11/tqt3-libs
DEPENDS+=	tqt3-tools>=${TQT3_RELEASE}:../../x11/tqt3-tools
DEPENDS+=	tqt3-docs>=${TQT3_RELEASE}:../../x11/tqt3-docs
DEPENDS+=	tqt3-mysql>=${TQT3_RELEASE}:../../x11/tqt3-mysql
DEPENDS+=	tqt3-odbc>=${TQT3_RELEASE}:../../x11/tqt3-odbc
DEPENDS+=	tqt3-psql>=${TQT3_RELEASE}:../../x11/tqt3-psql
DEPENDS+=	tqt3-sqlite>=${TQT3_RELEASE}:../../x11/tqt3-sqlite
DEPENDS+=	tqt3-sqlite3>=${TQT3_RELEASE}:../../x11/tqt3-sqlite3

.include "../../mk/bsd.pkg.mk"
