# $NetBSD$

DISTNAME=	dibbler-1.0.1
CATEGORIES=	net
MASTER_SITES=	http://klub.com.pl/dhcpv6/dibbler/

HOMEPAGE=	http://klub.com.pl/dhcpv6/dibbler/
COMMENT=	Portable DHCPv6 implementation
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
